libfm_jni: Remove unused variables
 * libfm_jni/FmPerformanceParams.cpp:443:16:
    error: unused variable 'sinr'

 * libfm_jni/ConfigFmThs.cpp:425:17:
    error: unused variable 'ret'

 * libfm_jni/ConfigFmThs.cpp:433:9:
    error: unused variable 'value'

 * libfm_jni/ConfigFmThs.cpp:566:9:
    error: unused variable 'index'

 * libfm_jni/ConfFileParser.cpp:328:16:
    error: unused variable 'num_of_keys'

 * libfm_jni/ConfFileParser.cpp:536:9:
    error: unused variable 'grp_name'

 * libfm_jni/ConfFileParser.cpp:537:16:
    error: unused variable 'len'

 * libfm_jni/FmRadioController.cpp:651:9:
    error: unused variable 'stationList

 * libfm_jni/FmPerformanceParams.cpp:442:16:
    error: unused variable 'sinr'

 * libfm_jni/ConfFileParser.cpp:732:13:
    error: unused function 'key_exist'

Change-Id: I9c4839d1bc8b64c536b8a7db7c2094001f2562ba