libfm_jni: Ignore unused parameters from APIs
 * libfm_jni/LibfmJni.cpp:163:41:
    error: unused parameter 'thiz'

 * libfm_jni/LibfmJni.cpp:95:50:
    error: unused parameter 'env'

 * libfm_jni/LibfmJni.cpp:95:50:
    error: unused parameter 'type'

 * Cleanup the indentation from JNI_OnLoad
    and register_android_hardware_fm

Change-Id: Ieebc105f3eb7ed5bd668e758aa0b001c78fafca7