fm: Resolve required dependency qcom.fmradio.xml linkage
 * LOCAL_REQUIRED_MODULES should be used instead of
    LOCAL_ADDITIONAL_DEPENDENCIES to link a module

 * fm/Android.mk:
    error: qcom.fmradio: LOCAL_ADDITIONAL_DEPENDENCIES
    must only contain paths (not module names)

Change-Id: Ic0bebf752101f5d16abc52e085bae4acd0b0c61c